title: Jardel's Blog
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "jardsantos.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jardel Santos # add your name
author-img: jardelsantos.jpeg # add your photo
about-author: | "Data Scientist.\nbreak line test\nbreak 2" # add description
social-github: jardsantos # add your Github handle
social-linkedin: jardel-santos-87823a95 # add your Linkedin handle
social-email: jardelsantos44@gmail.com # add your Email address
social-instagram: jardelsantos92

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
